reformat UI
GarikHarutyunyan/type-mastery pull request #11
Opened 2023-07-28 09:58 UTC by Kost333

Minior fix

2023-07-31 16:07 UTC, Kost333 commented on src/pages/header/Header.tsx
Sign in change to sign up

2023-07-31 16:08 UTC, Kost333 commented on src/pages/header/Header.tsx
> +              <Link to="/">Log In</Link>
change 'Logn In' to 'Sign In'

2023-08-04 20:38 UTC, vaahe commented on src/components/LightDarkMode/DarkMode.css
change file to modular css

2023-08-04 20:56 UTC, vaahe commented on src/components/LightDarkMode/DarkMode.tsx
> +    const dispatch: ThunkDispatch<RootState, any, any> = useDispatch();
change 'any' to valid type or interface

2023-08-04 20:56 UTC, vaahe commented on src/components/LightDarkMode/DarkMode.tsx
> +        if (theme === "dark") {
we can convert if/else block to ternary operator for less code

2023-08-04 20:56 UTC, vaahe commented on src/components/RegistrationModal/SignIn/SignIn.module.css
> +.Registration {
why classname begins with capital letter?

2023-08-04 20:56 UTC, vaahe commented on src/components/RegistrationModal/SignIn/SignIn.tsx
> +                    <div style={{display: "flex", alignItems: "flex-start", justifyContent: "flex-end", width: "100%", height:"100%"}}>
prevent to inline styles

2023-08-04 20:56 UTC, vaahe commented on src/components/RegistrationModal/SignIn/SignIn.tsx
> +                               onChange={e => setState({...state, email: e.target.value})}/>
on my opinion it will be more efficient to write separate handler function

2023-08-09 16:23 UTC, GarikHarutyunyan requested changes

2023-08-09 16:23 UTC, GarikHarutyunyan commented on src/components/LightDarkMode/DarkMode.tsx
> +    const defaultDark = storedTheme === "dark" || (storedTheme === null && prefersDark);
If I'm not mistaken we have coresponding enum for 'dark' and 'light'

2023-08-09 16:23 UTC, GarikHarutyunyan commented on src/components/LightDarkMode/DarkMode.tsx
> +    const prefersDark =
please explain this

2023-08-09 16:23 UTC, GarikHarutyunyan commented on src/components/LightDarkMode/DarkMode.tsx
> +        document.documentElement.setAttribute("data-theme", "dark");
Why do you need to directly work with dom? We must avoid this kind of things

2023-08-09 16:23 UTC, GarikHarutyunyan commented on src/components/LightDarkMode/DarkMode.tsx
> +        if (theme === "dark") {
It makes sens to use ternary operator if we need something in the same line, 
e.g. const text = showInfo ?   info : placeholder

otherwise it is better to use if and else, or switch

2023-08-09 16:23 UTC, GarikHarutyunyan commented on src/components/LightDarkMode/DarkMode.tsx
> +    // Update the state based on the subscribed value
Code itself must be readable and understandable to avoid comments. If it is not easy to understand what actually code does you need to change code, othewise just remove comment.

2023-08-09 16:23 UTC, GarikHarutyunyan commented on src/components/RegistrationModal/RegistrationModal.tsx
> +    const modalContent = (
Why don't you use aleardy created Modal component?

2023-08-09 16:23 UTC, GarikHarutyunyan commented on src/components/RegistrationModal/RegistrationModal.tsx
> +const RegistrationModal = ({isVisible, onClose}: IModalProps) => {
Isn't 'registartion' mean only signing up? Why does it also cover sign in?

2023-08-09 16:23 UTC, GarikHarutyunyan commented on src/components/RegistrationModal/RegistrationModal.tsx
> +            {window.location.pathname === '/signIn' ? <SignIn onClose={onClose}/> : <SignUp onClose={onClose}/>}
Why do you use window.location.pathname? in React we used to use React Router for routing

2023-08-09 16:23 UTC, GarikHarutyunyan commented on src/components/RegistrationModal/SignIn/SignIn.module.css
> +.COMPANY {
?

2023-08-09 16:23 UTC, GarikHarutyunyan commented on src/components/RegistrationModal/SignIn/SignIn.tsx
> +                    <div style={{display: "flex", alignItems: "flex-start", justifyContent: "flex-end", width: "100%", height:"100%"}}>
right, use classNames

2023-08-09 16:23 UTC, GarikHarutyunyan commented on src/store/app/appStylesSlice.ts
> +export const appStylesSlice = createSlice({
It was initially design to keep information regarding theme in context, @vaahe correct me if I'm wrong, @Kost333 why do you change the logic to use slice?

2023-08-09 16:23 UTC, GarikHarutyunyan commented on src/index.tsx
> +import { Provider } from 'react-redux';
You are using 'react-redux', but you didn't add it to package.json

2023-08-20 16:00 UTC, merged